# Generated by Django 5.0 on 2023-12-13 19:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mypets', '0004_alter_genre_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='publisher',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
    ]
