# Generated by Django 5.0 on 2023-12-13 19:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mypets', '0006_alter_book_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='publisher',
            name='address',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
    ]
