# Generated by Django 5.0 on 2023-12-13 19:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mypets', '0007_alter_publisher_address'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='publisher',
            name='description',
        ),
        migrations.AlterField(
            model_name='publisher',
            name='name',
            field=models.CharField(max_length=150, unique=True),
        ),
    ]
